# Generated by Django 3.1.7 on 2021-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=50)),
                ('author', models.TextField(blank=True, max_length=50)),
                ('Edition', models.TextField(blank=True, max_length=50)),
                ('branch', models.TextField(blank=True, max_length=50)),
                ('book_pdf', models.FileField(blank=True, max_length=50, upload_to='')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
