# Generated by Django 3.1.7 on 2021-04-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Edition',
            new_name='edition',
        ),
    ]
