# Generated by Django 3.1.7 on 2021-04-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210403_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='branch',
            field=models.CharField(blank=True, choices=[('computer_engineering', 'Computer Engineering'), ('IT', 'I.T.'), ('electronics and telecommunication', 'Electronics and Telecommunication')], max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default.png', upload_to='books/images/'),
        ),
    ]
